# Generated by Django 5.0.6 on 2024-07-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tipoProducto', models.CharField(max_length=40)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precioProducto', models.CharField(max_length=5)),
                ('imagenProducto', models.ImageField(upload_to='imagenes/')),
                ('stockProducto', models.IntegerField()),
            ],
        ),
    ]
