# Generated by Django 5.0.6 on 2024-07-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaLibretitas', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('idVenta', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('fechaVenta', models.DateField()),
                ('rutCliente', models.ForeignKey(db_column='rutCliente', on_delete=django.db.models.deletion.CASCADE, to='paginaLibretitas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idProducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='paginaLibretitas.producto')),
                ('idVenta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, to='paginaLibretitas.venta')),
            ],
        ),
    ]
